BRR_Sample3: ;new thunderforce
.incbin "music/data3_sample0.brr" 
.incbin "music/data3_sample1.brr" 
.incbin "music/data3_sample2.brr" 
.incbin "music/data3_sample3.brr" 
.incbin "music/data3_sample4.brr" 
.incbin "music/data3_sample5.brr" 
.incbin "music/data3_sample6.brr" 
.incbin "music/data3_sample7.brr" 
.incbin "music/data3_sample8.brr" 
.incbin "music/data3_sample9.brr" 
.incbin "music/data3_sample10.brr" 
.incbin "music/data3_sample11.brr" 
.incbin "music/data3_sample12.brr" 
.incbin "music/data3_sample13.brr" 
.incbin "music/data3_sample14.brr" 
.incbin "music/data3_sample15.brr" 
.incbin "music/data3_sample24.brr" 
.incbin "music/data3_sample25.brr" 
.incbin "music/data3_sample26.brr" 
.incbin "music/data3_sample27.brr" 
.incbin "music/data3_sample28.brr" 
.incbin "music/data3_sample29.brr" 
BRR_Sample3EOF:
