sfx_load: ;SFX

	;SFX
	LKS_SPC_Set2 LKS_SPC_ADDR,$c000
	LKS_SPC_SetD BRR_SFX,BRR_SFXEOF-BRR_SFX

	;SFXDIR
	LKS_SPC_Set2 LKS_SPC_ADDR,LKS_SPC_SFXDIR
	LKS_SPC_SetD BRR_SFXDIR,BRR_SFXDIREOF-BRR_SFXDIR

	rts
